# dummy_config:
#   test: true
AUGMENTATION: True
IMAGE_SIZE: [224, 224,3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 2
CLASSES: 2
WEIGHTS: imagenet
params_learning_rate: 0.001

LEARNING_RATE: 0.001